env:
  browser: true
  es6: true
  jasmine: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 8
  ecmaFeatures:
    experimentalObjectRestSpread: true
  sourceType: module
rules:
  indent:
    - error
    - 4
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-cond-assign:
    - warn
  no-unused-vars:
    - warn
