env:
  browser: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 8
  ecmaFeatures:
    experimentalObjectRestSpread: true
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-cond-assign:
    - warn
